### ISSUE TITLE
Request on an Example to add a video into a playlist

### ISSUE THREAD

**Issue by Rp70** [frelo/fvc#1]
Hi,

We're evaluating the Fast Video Cataloger. We are coding a .cs script which searchs videos and applies some more tasks. Then finally it adds them to a new playlist. What we are experiencing is we don't see any methods to create a VideoClip object to add to a playlist.

The code we currently have:
```csharp
// Create a new playlist
int PlayListID = catalog.CreateVideoPlaylist("New playlist");

// Create a VideoClip
// HOW TO create it?
// We don't see any methods to create a VideoClip object
// Is this the right way?
VideoClip clip = new VideoClip();
clip.StartTime = 0;
clip.EndTime = video_entry.LengthSeconds;
clip.VideoFileID = video_entry.ID;

// Get the clip ID
int clipid = catalog.SetVideoClip(clip);

// Add the clip to the newly created playlist
catalog.SetClipToPlaylist(PlayListID, 0, clipid);
```
Is that the correct way to it a video to a playlist?

Fast Video Cataloger version: v7.0.0.0 trial

Please advise.

**Comment by frelo** [comment]
Thanks for the feedback! 

Yes, we will add a sample for the playlist. 

Just add this line: 

clip.ID = -1; 

to your initialization of the clip object and it should work. ( I make sure the documentation is updated as well for the next release). Set it to the id of a clip if you want to update the clip.

**Comment by Rp70** [comment]
> Just add this line:
> 
> clip.ID = -1;

This works perfectly. Thank you!

By the way, I want to add some more feedback:

1. DeleteVideoClip() seems not to remove the specified clip from the catalog.
```csharp
int[] all_clip_ids = catalog.GetPlaylistClipIDs(PlaylistID);
foreach (int clipid in all_clip_ids) {
    catalog.RemovePlaylistClip(PlaylistID, clipid);
    catalog.DeleteVideoClip(clipid);

    // The below GetVideoClip() still return the removed object.
    VideoClip clip = catalog.GetVideoClip(clipid);
    m_scripting.GetConsole().WriteLine("VideoClip: " +  clip.ID);
}
catalog.DeletePlaylist(PlaylistID);
```

2. GetGUI().Refresh("") doesn't work for playlist.
```csharp
// This only works on sample of Bin as sampled at https://github.com/frelo/fvc/blame/a82b7ba10ae2082ddff4e82824fbda1676d1538e/samples/filter_to_bin.cs#L82
m_scripting.GetGUI().Refresh("");
```
So I have to create a new playlist (eg: playlist name: "asdfasdfasdfasdf"), then delete that playlist to allow catalog GUI to refresh the playlist list.

**Comment by frelo** [comment]
1. Hmm thanks, We will investigate, that should work.

2. Yes, you are correct Refresh() does not refresh the Playlists. That is fixed in the next update (Now you need to do something manually in the UI to get it to refresh).

**Comment by frelo** [comment]
1. I verified this and you are correct. A fix will be in the next update.

2. We have added refresh to playlists and the latest verison 7.02 has that fix.

**Comment by Rp70** [comment]
Thank you!
